/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App{
    public static void main(String[] args) {
        // create cuties
        Puppy puppy = new Puppy();
        Kitty kitty = new Kitty();
        PygmyMarmoset pygmyMarmoset = new PygmyMarmoset();

        // create queue
        QueueTees queue = new QueueTees(3);

        // enqueue cuties
        queue.enqueue(puppy);
        queue.enqueue(kitty);
        queue.enqueue(pygmyMarmoset);

        System.out.println(queue.size());

         // dequeue cuties
        queue.dequeue();
        queue.dequeue();
        queue.dequeue();
        
        System.out.println(queue.size());
    }
}

class Puppy implements Cutie {
    public String description() { return "A small excited puppy"; }
    public Integer cutenessRating() { return 10; }
}

class Kitty implements Cutie {
    public String description() { return "A fluffy kitten"; }
    public Integer cutenessRating() { return 9; }
}

class PygmyMarmoset implements Cutie {
    public String description() { return "A tiny pygmy marmoset"; }
    public Integer cutenessRating() { return 10; }
}
